# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
    - name: 📂 Sync files with FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21 # Change if necessary
        local-dir: ./dist/ # Change if necessary
    # - name: FTP Deploy
    #   # You may pin to the exact commit or the version.
    #   # uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     # ftp server
    #     server: ${{ vars.FTP_SERVER }}
    #     # ftp username  @1FbmMAFWAsNTxY9
    #     username: ${{ vars.FTP_USER }}
    #     # ftp password
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     # Server port to connect to (read your web hosts docs)
    #     port: ${{ vars.FTP_PORT }}
    #     # protocol to deploy with - ftp, ftps, or ftps-legacy
    #     protocol: ftps-legacy
    #     # Folder to upload from, must end with trailing slash /
    #     local-dir: dist/
    #     # Path to upload to on the server. Must end with trailing slash /
    #     server-dir: /
    #     log-level: verbose

    
